package api

import "net/http"

func (a *App) registerRoutes() {
	a.add(http.MethodGet, "/", AuthPublic, a.handleRoot)
	a.add(http.MethodGet, "/api/v1/openapi.json", AuthPublic, a.handleOpenAPI)
	a.add(http.MethodGet, "/api/v1/docs", AuthPublic, a.handleDocs)

	a.add(http.MethodPost, "/api/v1/auth/login", AuthPublic, a.handleLogin)
	a.add(http.MethodPost, "/api/v1/auth/forgot-password/emby", AuthPublic, a.handleForgotPassword)
	a.add(http.MethodPost, "/api/v1/auth/login/telegram", AuthPublic, a.handleDirectLoginUnavailable)
	a.add(http.MethodPost, "/api/v1/auth/login/apikey", AuthPublic, a.handleLoginByAPIKey)
	a.add(http.MethodPost, "/api/v1/auth/logout", AuthUser, a.handleLogout)
	a.add(http.MethodPost, "/api/v1/auth/logout/all", AuthUser, a.handleLogoutAll)
	a.add(http.MethodGet, "/api/v1/auth/me", AuthUser, a.handleCurrentUser)
	a.add(http.MethodPost, "/api/v1/auth/refresh", AuthUser, a.handleRefresh)
	a.add(http.MethodGet, "/api/v1/auth/apikey", AuthUser, a.handleLegacyAPIKeyStatus)
	a.add(http.MethodPost, "/api/v1/auth/apikey", AuthUser, a.handleLegacyAPIKeyGenerate)
	a.add(http.MethodDelete, "/api/v1/auth/apikey", AuthUser, a.handleLegacyAPIKeyDelete)
	a.add(http.MethodPost, "/api/v1/auth/apikey/enable", AuthUser, a.handleLegacyAPIKeyEnable)
	a.add(http.MethodGet, "/api/v1/auth/apikey/permissions", AuthUser, a.handleLegacyAPIKeyPermissions)
	a.add(http.MethodPut, "/api/v1/auth/apikey/permissions", AuthUser, a.handleLegacyAPIKeyPermissionsUpdate)

	a.add(http.MethodPost, "/api/v1/users/register", AuthPublic, a.handleRegister)
	a.add(http.MethodGet, "/api/v1/users/check-available", AuthPublic, a.handleRegisterAvailability)
	a.add(http.MethodGet, "/api/v1/users/regcode/check", AuthPublic, a.handleRegcodeCheck)
	a.add(http.MethodGet, "/api/v1/users/telegram/register/bind-code", AuthPublic, a.handleRegisterBindCode)
	a.add(http.MethodGet, "/api/v1/users/telegram/register/bind-code/status", AuthPublic, a.handleBindCodeStatus)
	a.add(http.MethodGet, "/api/v1/users/telegram/register/bind-code/ws", AuthPublic, a.handleBindCodeStatusWS)
	a.add(http.MethodPost, "/api/v1/users/me/telegram/bind-confirm", AuthPublic, a.handleBindConfirmSecure)
	a.add(http.MethodGet, "/api/v1/users/register/emby/status", AuthPublic, a.handleQueueStatus)
	a.add(http.MethodGet, "/api/v1/users/me", AuthUser, a.handleCurrentUser)
	a.add(http.MethodPut, "/api/v1/users/me", AuthUser, a.handleUpdateMe)
	a.add(http.MethodPut, "/api/v1/users/me/username", AuthUser, a.handleUpdateUsername)
	a.add(http.MethodPut, "/api/v1/users/me/password", AuthUser, a.handleGeneratedPassword)
	a.add(http.MethodPost, "/api/v1/users/me/password/change", AuthUser, a.handleChangePassword)
	a.add(http.MethodPost, "/api/v1/users/me/password/system", AuthUser, a.handleChangePassword)
	a.add(http.MethodPost, "/api/v1/users/me/password/emby", AuthUser, a.handleChangeEmbyPassword)
	a.add(http.MethodPost, "/api/v1/users/me/emby/bind", AuthUser, a.handleBindEmby)
	a.add(http.MethodPost, "/api/v1/users/me/emby/register", AuthUser, a.handleRegisterEmby)
	a.add(http.MethodPost, "/api/v1/users/me/emby/unbind", AuthUser, a.handleUnbindEmby)
	a.add(http.MethodPost, "/api/v1/users/me/renew", AuthUser, a.handleRenew)
	a.add(http.MethodPost, "/api/v1/users/me/use-code", AuthUser, a.handleUseCode)
	a.add(http.MethodGet, "/api/v1/users/me/use-code/status", AuthUser, a.handleQueueStatus)
	a.add(http.MethodGet, "/api/v1/users/me/devices", AuthUser, a.handleDevices)
	a.add(http.MethodDelete, "/api/v1/users/me/devices/:device_id", AuthUser, a.handleDeleteDevice)
	a.add(http.MethodGet, "/api/v1/users/me/sessions", AuthUser, a.handleSessions)
	a.add(http.MethodGet, "/api/v1/users/me/login-history", AuthUser, a.handleLoginHistory)
	a.add(http.MethodGet, "/api/v1/users/me/telegram", AuthUser, a.handleTelegramStatus)
	a.add(http.MethodPost, "/api/v1/users/me/telegram/rebind-request", AuthUser, a.handleTelegramRebindRequest)
	a.add(http.MethodPost, "/api/v1/users/me/telegram/unbind", AuthUser, a.handleUnbindTelegram)
	a.add(http.MethodGet, "/api/v1/users/me/telegram/bind-code", AuthUser, a.handleUserBindCode)
	a.add(http.MethodGet, "/api/v1/users/me/settings", AuthUser, a.handleUserSettings)
	a.add(http.MethodGet, "/api/v1/users/:uid/background", AuthUser, a.handleGetBackground)
	a.add(http.MethodPut, "/api/v1/users/me/background", AuthUser, a.handleUpdateBackground)
	a.add(http.MethodDelete, "/api/v1/users/me/background", AuthUser, a.handleDeleteBackground)
	a.add(http.MethodPost, "/api/v1/users/me/background/upload", AuthUser, a.handleUploadBackground)
	a.add(http.MethodGet, "/api/v1/users/:uid/avatar", AuthUser, a.handleGetAvatar)
	a.add(http.MethodPost, "/api/v1/users/me/avatar/upload", AuthUser, a.handleUploadAvatar)
	a.add(http.MethodDelete, "/api/v1/users/me/avatar", AuthUser, a.handleDeleteAvatar)
	a.add(http.MethodGet, "/api/v1/users/assets/:kind/:filename", AuthUser, a.handleAsset)
	a.add(http.MethodGet, "/api/v1/users/me/apikeys", AuthUser, a.handleListAPIKeys)
	a.add(http.MethodPost, "/api/v1/users/me/apikeys", AuthUser, a.handleCreateAPIKey)
	a.add(http.MethodPut, "/api/v1/users/me/apikeys/:key_id", AuthUser, a.handleUpdateAPIKey)
	a.add(http.MethodDelete, "/api/v1/users/me/apikeys/:key_id", AuthUser, a.handleDeleteAPIKey)

	a.add(http.MethodGet, "/api/v1/system/info", AuthPublic, a.handleSystemInfo)
	a.add(http.MethodGet, "/api/v1/system/server-icon", AuthPublic, a.handleServerIcon)
	a.add(http.MethodGet, "/api/v1/system/health", AuthPublic, a.handleHealth)
	a.add(http.MethodGet, "/api/v1/system/stats", AuthAdmin, a.handleSystemStats)
	a.add(http.MethodGet, "/api/v1/system/emby-urls", AuthUser, a.handleEmbyURLs)
	a.add(http.MethodPost, "/api/v1/system/emby-urls/probe", AuthUser, a.handleEmbyURLProbe)
	a.add(http.MethodGet, "/api/v1/system/config", AuthUser, a.handlePublicConfig)
	a.add(http.MethodGet, "/api/v1/system/admin/config", AuthAdmin, a.handleAdminConfig)
	a.add(http.MethodGet, "/api/v1/system/admin/stats", AuthAdmin, a.handleSystemStats)
	a.add(http.MethodGet, "/api/v1/system/admin/runtime/status", AuthAdmin, a.handleRuntimeStatus)
	a.add(http.MethodGet, "/api/v1/system/admin/runtime/logs", AuthAdmin, a.handleRuntimeLogs)
	a.add(http.MethodGet, "/api/v1/system/admin/runtime/logs/stream", AuthAdmin, a.handleRuntimeLogStream)
	a.add(http.MethodPost, "/api/v1/system/admin/update", AuthAdmin, a.handleSystemUpdate)
	a.add(http.MethodPost, "/api/v1/system/admin/server-icon/upload", AuthAdmin, a.handleUploadServerIcon)
	a.add(http.MethodGet, "/api/v1/system/admin/database/status", AuthAdmin, a.handleDatabaseStatus)
	a.add(http.MethodGet, "/api/v1/system/admin/database/backups", AuthAdmin, a.handleDatabaseBackups)
	a.add(http.MethodGet, "/api/v1/system/admin/database/backups/:name", AuthAdmin, a.handleDatabaseBackupInspect)
	a.add(http.MethodDelete, "/api/v1/system/admin/database/backups/:name", AuthAdmin, a.handleDatabaseBackupDelete)
	a.add(http.MethodPost, "/api/v1/system/admin/database/backup", AuthAdmin, a.handleDatabaseBackup)
	a.add(http.MethodPost, "/api/v1/system/admin/database/restore", AuthAdmin, a.handleDatabaseRestore)
	a.add(http.MethodPost, "/api/v1/system/admin/database/migrate", AuthAdmin, a.handleDatabaseMigrate)
	a.add(http.MethodGet, "/api/v1/system/admin/config/toml", AuthAdmin, a.handleConfigTOMLGet)
	a.add(http.MethodPut, "/api/v1/system/admin/config/toml", AuthAdmin, a.handleConfigTOMLPutSafe)
	a.add(http.MethodGet, "/api/v1/system/admin/config/schema", AuthAdmin, a.handleConfigSchemaFull)
	a.add(http.MethodPut, "/api/v1/system/admin/config/schema", AuthAdmin, a.handleConfigSchemaUpdateSafe)
	a.add(http.MethodGet, "/api/v1/system/admin/config/backups", AuthAdmin, a.handleConfigBackups)
	a.add(http.MethodPost, "/api/v1/system/admin/config/backup", AuthAdmin, a.handleConfigBackup)
	a.add(http.MethodGet, "/api/v1/system/admin/config/backups/:name", AuthAdmin, a.handleConfigBackupInspect)
	a.add(http.MethodDelete, "/api/v1/system/admin/config/backups/:name", AuthAdmin, a.handleConfigBackupDelete)
	a.add(http.MethodPost, "/api/v1/system/admin/config/restore", AuthAdmin, a.handleConfigRestore)
	a.add(http.MethodPost, "/api/v1/system/admin/config/sweep", AuthAdmin, a.handleConfigSweep)
	a.add(http.MethodGet, "/api/v1/system/admin/apis", AuthAdmin, a.handleAPIRoutes)
	a.add(http.MethodPost, "/api/v1/system/admin/bot/test", AuthAdmin, a.handleBotTest)

	a.add(http.MethodGet, "/api/v1/emby/status", AuthUser, a.handleEmbyStatus)
	a.add(http.MethodGet, "/api/v1/emby/urls", AuthPublic, a.handleDeprecatedEmbyURLs)
	a.add(http.MethodGet, "/api/v1/emby/search", AuthUser, a.handleMediaSearch)
	a.add(http.MethodGet, "/api/v1/emby/latest", AuthUser, a.handleEmbyLatest)
	a.add(http.MethodGet, "/api/v1/emby/sessions/count", AuthUser, a.handleSessionCount)
	a.add(http.MethodPost, "/api/v1/emby/bangumi/webhook", AuthPublic, a.handleBangumiWebhook)

	a.add(http.MethodGet, "/api/v1/media/search", AuthUser, a.handleMediaSearch)
	a.add(http.MethodGet, "/api/v1/media/search/tmdb", AuthUser, a.handleMediaSearch)
	a.add(http.MethodGet, "/api/v1/media/search/bangumi", AuthUser, a.handleMediaSearch)
	a.add(http.MethodGet, "/api/v1/media/search/id/:source_type/:media_id", AuthUser, a.handleMediaDetail)
	a.add(http.MethodGet, "/api/v1/media/detail", AuthUser, a.handleMediaDetail)
	a.add(http.MethodGet, "/api/v1/media/tmdb/:tmdb_id", AuthUser, a.handleMediaDetail)
	a.add(http.MethodGet, "/api/v1/media/bangumi/:bgm_id", AuthUser, a.handleMediaDetail)
	a.add(http.MethodPost, "/api/v1/media/inventory/check", AuthUser, a.handleInventoryCheck)
	a.add(http.MethodGet, "/api/v1/media/inventory/search", AuthUser, a.handleInventorySearch)
	a.add(http.MethodPost, "/api/v1/media/request", AuthUser, a.handleCreateMediaRequest)
	a.add(http.MethodGet, "/api/v1/media/request/my", AuthUser, a.handleMyMediaRequests)
	a.add(http.MethodGet, "/api/v1/media/request/pending", AuthAdmin, a.handleAdminMediaRequests)
	a.add(http.MethodPut, "/api/v1/media/request/:request_id/status", AuthAdmin, a.handleUpdateMediaRequestStatus)
	a.add(http.MethodPost, "/api/v1/media/request/external/update", AuthPublic, a.handleExternalMediaUpdate)
	a.add(http.MethodGet, "/api/v1/media/request/by-key/:require_key", AuthUser, a.handleMediaRequestByKey)
	a.add(http.MethodDelete, "/api/v1/media/request/by-key/:require_key", AuthUser, a.handleDeleteMediaRequestByKey)
	a.add(http.MethodGet, "/api/v1/media/request/:request_id", AuthUser, a.handleMediaRequestByID)
	a.add(http.MethodDelete, "/api/v1/media/request/:request_id", AuthUser, a.handleDeleteMediaRequest)

	a.registerAdminRoutes()
	a.registerAPIKeyRoutes()
	a.registerSecurityRoutes()
	a.registerBatchRoutes()
	a.registerStatsInviteSigninAnnouncementRoutes()
}

func (a *App) registerAdminRoutes() {
	a.add(http.MethodGet, "/api/v1/admin/users", AuthAdmin, a.handleAdminUsers)
	a.add(http.MethodPost, "/api/v1/admin/users", AuthAdmin, a.handleAdminCreateUser)
	a.add(http.MethodPut, "/api/v1/admin/me/update", AuthAdmin, a.handleUpdateMe)
	a.add(http.MethodGet, "/api/v1/admin/users/:uid", AuthAdmin, a.handleAdminUser)
	a.add(http.MethodPut, "/api/v1/admin/users/:uid", AuthAdmin, a.handleAdminUpdateUser)
	a.add(http.MethodDelete, "/api/v1/admin/users/:uid", AuthAdmin, a.handleAdminDeleteUser)
	a.add(http.MethodPost, "/api/v1/admin/users/:uid/delete", AuthAdmin, a.handleAdminDeleteUser)
	a.add(http.MethodPost, "/api/v1/admin/users/:uid/disable", AuthAdmin, a.handleAdminToggleUser)
	a.add(http.MethodPost, "/api/v1/admin/users/:uid/enable", AuthAdmin, a.handleAdminToggleUser)
	a.add(http.MethodDelete, "/api/v1/admin/users/:uid/emby", AuthAdmin, a.handleAdminUnbindEmby)
	a.add(http.MethodPost, "/api/v1/admin/users/:uid/force-unbind", AuthAdmin, a.handleAdminForceUnbind)
	a.add(http.MethodPost, "/api/v1/admin/users/:uid/registration-queue/clear", AuthAdmin, a.handleRegistrationQueueClear)
	a.add(http.MethodPost, "/api/v1/admin/users/registration-queue/clear", AuthAdmin, a.handleRegistrationQueueClear)
	a.add(http.MethodPost, "/api/v1/admin/users/registration-queue/grant-entitlement-and-clear", AuthAdmin, a.handleRegistrationEntitlementBulk)
	a.add(http.MethodPost, "/api/v1/admin/users/:uid/registration-entitlement", AuthAdmin, a.handleRegistrationEntitlement)
	a.add(http.MethodPost, "/api/v1/admin/users/:uid/registration-entitlement/dequeue", AuthAdmin, a.handleRegistrationEntitlement)
	a.add(http.MethodPost, "/api/v1/admin/users/sync-bindings", AuthAdmin, a.handleSyncBindings)
	a.add(http.MethodPost, "/api/v1/admin/users/:uid/renew", AuthAdmin, a.handleAdminRenewUser)
	a.add(http.MethodPost, "/api/v1/admin/users/:uid/cancel-permanent", AuthAdmin, a.handleAdminRenewUser)
	a.add(http.MethodPost, "/api/v1/admin/users/:uid/reset-password", AuthAdmin, a.handleAdminResetPassword)
	a.add(http.MethodPost, "/api/v1/admin/users/:uid/kick", AuthAdmin, a.handleKickUser)
	a.add(http.MethodPut, "/api/v1/admin/users/:uid/admin", AuthAdmin, a.handleAdminSetRole)
	a.add(http.MethodPost, "/api/v1/admin/users/:uid/unbind-telegram", AuthAdmin, a.handleAdminUnbindTelegram)
	a.add(http.MethodPost, "/api/v1/admin/users/:uid/bind-telegram", AuthAdmin, a.handleAdminBindTelegram)
	a.add(http.MethodGet, "/api/v1/admin/users/by-telegram/:telegram_id", AuthAdmin, a.handleUserByTelegram)
	a.add(http.MethodPost, "/api/v1/admin/emby/force-set-password", AuthAdmin, a.handleAdminResetPassword)
	a.add(http.MethodPost, "/api/v1/admin/emby/sync", AuthAdmin, a.handleEmbySyncV2)
	a.add(http.MethodGet, "/api/v1/admin/emby/sessions", AuthAdmin, a.handleSessions)
	a.add(http.MethodGet, "/api/v1/admin/emby/activity", AuthAdmin, a.handleEmbyActivity)
	a.add(http.MethodGet, "/api/v1/admin/emby/users", AuthAdmin, a.handleAdminEmbyUsersV2)
	a.add(http.MethodPost, "/api/v1/admin/emby/broadcast", AuthAdmin, a.handleEmbyBroadcast)
	a.add(http.MethodPost, "/api/v1/admin/emby/test", AuthAdmin, a.handleEmbyTestV2)
	a.add(http.MethodPost, "/api/v1/admin/emby/cleanup-orphans", AuthAdmin, a.handleEmbyCleanupOrphans)
	a.add(http.MethodPost, "/api/v1/admin/emby/import-users", AuthAdmin, a.handleEmbyImportUsers)
	a.add(http.MethodPost, "/api/v1/admin/emby/reset-bindings", AuthAdmin, a.handleEmbyResetBindings)
	a.add(http.MethodPost, "/api/v1/admin/emby/delete-unlinked", AuthAdmin, a.handleEmbyDeleteUnlinked)
	a.add(http.MethodPost, "/api/v1/admin/emby/create-standalone", AuthAdmin, a.handleCreateStandaloneEmbyV2)
	a.add(http.MethodPost, "/api/v1/admin/users/:uid/bind-emby", AuthAdmin, a.handleAdminBindEmby)
	a.add(http.MethodGet, "/api/v1/admin/regcodes", AuthAdmin, a.handleListRegcodes)
	a.add(http.MethodPost, "/api/v1/admin/regcodes", AuthAdmin, a.handleCreateRegcodes)
	a.add(http.MethodPost, "/api/v1/admin/regcodes/batch-delete", AuthAdmin, a.handleBatchDeleteRegcodes)
	a.add(http.MethodPut, "/api/v1/admin/regcodes/:code", AuthAdmin, a.handleUpdateRegcode)
	a.add(http.MethodDelete, "/api/v1/admin/regcodes/:code", AuthAdmin, a.handleDeleteRegcode)
	a.add(http.MethodGet, "/api/v1/admin/regcodes/:code/users", AuthAdmin, a.handleRegcodeUsers)
	a.add(http.MethodPost, "/api/v1/admin/regcodes/:code/clear-usage", AuthAdmin, a.handleClearRegcodeUsage)
	a.add(http.MethodGet, "/api/v1/admin/media-requests", AuthAdmin, a.handleAdminMediaRequests)
	a.add(http.MethodPut, "/api/v1/admin/media-requests/:request_id", AuthAdmin, a.handleUpdateMediaRequestStatus)
	a.add(http.MethodDelete, "/api/v1/admin/media-requests/:request_id", AuthAdmin, a.handleDeleteMediaRequest)
	a.add(http.MethodPut, "/api/v1/admin/media-requests/by-key/:require_key", AuthAdmin, a.handleUpdateMediaRequestByKey)
	a.add(http.MethodDelete, "/api/v1/admin/media-requests/by-key/:require_key", AuthAdmin, a.handleDeleteMediaRequestByKey)
	a.add(http.MethodPost, "/api/v1/admin/whitelist", AuthAdmin, a.handleWhitelist)
	a.add(http.MethodGet, "/api/v1/admin/stats", AuthAdmin, a.handleSystemStats)
	a.add(http.MethodPost, "/api/v1/admin/users/bulk-expire", AuthAdmin, a.handleAdminBulkExpire)
	a.add(http.MethodPost, "/api/v1/admin/users/bulk-enable-disabled", AuthAdmin, a.handleAdminBulkEnableDisabled)
	a.add(http.MethodPost, "/api/v1/admin/users/cleanup-invalid", AuthAdmin, a.handleAdminCleanupInvalid)
	a.add(http.MethodPost, "/api/v1/admin/users/clear-stale-pending-emby", AuthAdmin, a.handleAdminClearStalePendingEmby)
	a.add(http.MethodPost, "/api/v1/admin/users/clear-emails", AuthAdmin, a.handleAdminClearUserEmails)
	a.add(http.MethodPost, "/api/v1/admin/users/kick-no-emby", AuthAdmin, a.handleAdminKickNoEmby)
	a.add(http.MethodGet, "/api/v1/admin/invite/tree", AuthAdmin, a.handleInviteTree)
	a.add(http.MethodPost, "/api/v1/admin/invite/users/:uid/detach", AuthAdmin, a.handleInviteDetach)
	a.add(http.MethodGet, "/api/v1/admin/invite/codes", AuthAdmin, a.handleAdminInviteCodes)
	a.add(http.MethodGet, "/api/v1/admin/violations", AuthAdmin, a.handleListViolations)
	a.add(http.MethodDelete, "/api/v1/admin/violations/:violation_id", AuthAdmin, a.handleDeleteViolation)
	a.add(http.MethodPost, "/api/v1/admin/violations/clear", AuthAdmin, a.handleClearViolations)
	a.add(http.MethodGet, "/api/v1/admin/telegram/rebind-requests", AuthAdmin, a.handleListRebindRequests)
	a.add(http.MethodPost, "/api/v1/admin/telegram/rebind-requests/:request_id/approve", AuthAdmin, a.handleReviewRebindRequest)
	a.add(http.MethodPost, "/api/v1/admin/telegram/rebind-requests/:request_id/reject", AuthAdmin, a.handleReviewRebindRequest)
	a.add(http.MethodPost, "/api/v1/admin/telegram/rebind-requests/batch", AuthAdmin, a.handleBatchReviewRebindRequests)
	a.add(http.MethodGet, "/api/v1/admin/telegram/roster/stats", AuthAdmin, a.handleTelegramRosterStats)
	a.add(http.MethodPost, "/api/v1/admin/telegram/rejoined-users/enable", AuthAdmin, a.handleTelegramRejoinedEnable)
	a.add(http.MethodPost, "/api/v1/admin/telegram/kick-unbound", AuthAdmin, a.handleTelegramKickUnbound)
	a.add(http.MethodGet, "/api/v1/admin/scheduler/jobs", AuthAdmin, a.handleSchedulerJobs)
	a.add(http.MethodPost, "/api/v1/admin/scheduler/jobs/:job_id/run", AuthAdmin, a.handleSchedulerRunV2)
	a.add(http.MethodPost, "/api/v1/admin/scheduler/jobs/:job_id/terminate", AuthAdmin, a.handleSchedulerTerminate)
	a.add(http.MethodGet, "/api/v1/admin/scheduler/jobs/:job_id/last-run", AuthAdmin, a.handleSchedulerLastRun)
	a.add(http.MethodGet, "/api/v1/admin/scheduler/jobs/:job_id/history", AuthAdmin, a.handleSchedulerHistory)
	a.add(http.MethodPut, "/api/v1/admin/scheduler/jobs/:job_id/schedule", AuthAdmin, a.handleSchedulerSchedule)
	a.add(http.MethodDelete, "/api/v1/admin/scheduler/jobs/:job_id/schedule", AuthAdmin, a.handleSchedulerSchedule)
	a.add(http.MethodGet, "/api/v1/admin/announcements", AuthAdmin, a.handleAdminAnnouncements)
	a.add(http.MethodPost, "/api/v1/admin/announcements", AuthAdmin, a.handleCreateAnnouncement)
	a.add(http.MethodPut, "/api/v1/admin/announcements/:announcement_id", AuthAdmin, a.handleUpdateAnnouncement)
	a.add(http.MethodDelete, "/api/v1/admin/announcements/:announcement_id", AuthAdmin, a.handleDeleteAnnouncement)
}

func (a *App) registerAPIKeyRoutes() {
	a.add(http.MethodGet, "/api/v1/apikey/info", AuthAPIKey, a.handleAPIKeyInfo)
	a.add(http.MethodGet, "/api/v1/apikey/status", AuthAPIKey, a.handleAPIKeyStatus)
	a.add(http.MethodPost, "/api/v1/apikey/enable", AuthAPIKey, a.handleAPIKeyEnableAccount)
	a.add(http.MethodPost, "/api/v1/apikey/disable", AuthAPIKey, a.handleAPIKeyDisableAccount)
	a.add(http.MethodPost, "/api/v1/apikey/renew", AuthAPIKey, a.handleAPIKeyRenew)
	a.add(http.MethodPost, "/api/v1/apikey/key/refresh", AuthAPIKey, a.handleLegacyAPIKeyGenerate)
	a.add(http.MethodGet, "/api/v1/apikey/permissions", AuthAPIKey, a.handleAPIKeyPermissions)
	a.add(http.MethodPut, "/api/v1/apikey/permissions", AuthAPIKey, a.handleForbiddenSelfPermission)
	a.add(http.MethodPost, "/api/v1/apikey/key/disable", AuthAPIKey, a.handleAPIKeyDisableKey)
	a.add(http.MethodPost, "/api/v1/apikey/key/enable", AuthAPIKey, a.handleAPIKeyEnableKey)
	a.add(http.MethodGet, "/api/v1/apikey/emby/status", AuthAPIKey, a.handleEmbyStatus)
	a.add(http.MethodPost, "/api/v1/apikey/emby/kick", AuthAPIKey, a.handleAPIKeyEmbyKick)
	a.add(http.MethodPost, "/api/v1/apikey/use-code", AuthAPIKey, a.handleUseCode)
}

func (a *App) registerSecurityRoutes() {
	a.add(http.MethodGet, "/api/v1/security/devices", AuthUser, a.handleDevices)
	a.add(http.MethodPost, "/api/v1/security/devices/:device_id/block", AuthUser, a.handleBlockDevice)
	a.add(http.MethodPost, "/api/v1/security/devices/:device_id/trust", AuthUser, a.handleTrustDevice)
	a.add(http.MethodGet, "/api/v1/security/login-history", AuthUser, a.handleLoginHistory)
	a.add(http.MethodGet, "/api/v1/security/login-history/:uid", AuthAdmin, a.handleLoginHistory)
	a.add(http.MethodGet, "/api/v1/security/ip/blacklist", AuthAdmin, a.handleIPBlacklist)
	a.add(http.MethodPost, "/api/v1/security/ip/blacklist", AuthAdmin, a.handleAddIPBlacklist)
	a.add(http.MethodDelete, "/api/v1/security/ip/blacklist", AuthAdmin, a.handleDeleteIPBlacklist)
	a.add(http.MethodGet, "/api/v1/security/suspicious", AuthAdmin, a.handleSuspicious)
	a.add(http.MethodGet, "/api/v1/security/users/:uid/devices", AuthAdmin, a.handleDevices)
	a.add(http.MethodPost, "/api/v1/security/users/:uid/devices/:device_id/block", AuthAdmin, a.handleBlockDevice)
}

func (a *App) registerBatchRoutes() {
	a.add(http.MethodPost, "/api/v1/batch/users/disable", AuthAdmin, a.handleBatchDisableUsers)
	a.add(http.MethodPost, "/api/v1/batch/users/enable", AuthAdmin, a.handleBatchEnableUsers)
	a.add(http.MethodPost, "/api/v1/batch/users/renew", AuthAdmin, a.handleBatchRenewUsers)
	a.add(http.MethodPost, "/api/v1/batch/users/delete", AuthAdmin, a.handleBatchDeleteUsers)
	a.add(http.MethodPost, "/api/v1/batch/users/emby-unbind-lock", AuthAdmin, a.handleBatchLockEmbyUnbind)
	a.add(http.MethodGet, "/api/v1/batch/export/users", AuthAdmin, a.handleExportUsers)
	a.add(http.MethodGet, "/api/v1/batch/export/playback", AuthAdmin, a.handleExportPlayback)
	a.add(http.MethodGet, "/api/v1/batch/watch-stats", AuthUser, a.handleWatchStats)
	a.add(http.MethodGet, "/api/v1/batch/watch-stats/:uid", AuthAdmin, a.handleWatchStats)
	a.add(http.MethodGet, "/api/v1/batch/watch-stats/global", AuthAdmin, a.handleWatchStats)
	a.add(http.MethodGet, "/api/v1/batch/expiring-users", AuthAdmin, a.handleExpiringUsers)
	a.add(http.MethodPost, "/api/v1/batch/send-reminders", AuthAdmin, a.handleSendReminders)
}

func (a *App) registerStatsInviteSigninAnnouncementRoutes() {
	a.add(http.MethodGet, "/api/v1/stats/me", AuthUser, a.handleWatchStats)
	a.add(http.MethodGet, "/api/v1/stats/user/:uid", AuthAdmin, a.handleWatchStats)
	a.add(http.MethodGet, "/api/v1/invite/config", AuthPublic, a.handleInviteConfig)
	a.add(http.MethodGet, "/api/v1/invite/me", AuthUser, a.handleInviteMe)
	a.add(http.MethodPost, "/api/v1/invite/codes", AuthUser, a.handleCreateInviteCode)
	a.add(http.MethodPost, "/api/v1/invite/renew-codes", AuthUser, a.handleCreateInviteCode)
	a.add(http.MethodGet, "/api/v1/invite/codes", AuthUser, a.handleInviteCodes)
	a.add(http.MethodDelete, "/api/v1/invite/codes/:code", AuthUser, a.handleDeleteInviteCode)
	a.add(http.MethodPost, "/api/v1/invite/children/:uid/detach-expired", AuthUser, a.handleDetachExpiredInviteChild)
	a.add(http.MethodGet, "/api/v1/invite/check", AuthPublic, a.handleInviteCheck)
	a.add(http.MethodPost, "/api/v1/invite/use", AuthUser, a.handleInviteUse)
	a.add(http.MethodGet, "/api/v1/signin/config", AuthPublic, a.handleSigninConfig)
	a.add(http.MethodGet, "/api/v1/signin/me", AuthUser, a.handleSigninMe)
	a.add(http.MethodPost, "/api/v1/signin", AuthUser, a.handleSignin)
	a.add(http.MethodPost, "/api/v1/signin/renew", AuthUser, a.handleSigninRenew)
	a.add(http.MethodGet, "/api/v1/signin/history", AuthUser, a.handleSigninHistory)
	a.add(http.MethodGet, "/api/v1/announcements", AuthPublic, a.handleAnnouncements)
}
